const initialState = {
  data: [
    {
      id: '26007351216',
      user_id: '7236692',
      user_name: 'BillyBob',
      game_id: '29307',
      type: 'live',
      title: "[Punday Monday] Necromancer - Dan's First Character - Maps - !build",
      viewer_count: 5723,
      started_at: '2017-08-14T15:45:17Z',
      language: 'en',
      thumbnail_url: 'https://static-cdn.jtvnw.net/previews-ttv/live_user_dansgaming-{width}x{height}.jpg',
    },
    {
      id: '222222222',
      user_id: '7236692',
      user_name: 'BillyBob2',
      game_id: '29307',
      type: 'live',
      title: "[Punday Monday] Necromancer - Dan's First Character - Maps - !build",
      viewer_count: 5723,
      started_at: '2017-08-14T15:45:17Z',
      language: 'en',
      thumbnail_url: 'https://static-cdn.jtvnw.net/previews-ttv/live_user_dansgaming-{width}x{height}.jpg',
    },
    {
      id: '3333333333',
      user_id: '7236692',
      user_name: 'BillyBob3',
      game_id: '29307',
      type: 'live',
      title: "[Punday Monday] Necromancer - Dan's First Character - Maps - !build",
      viewer_count: 5723,
      started_at: '2017-08-14T15:45:17Z',
      language: 'en',
      thumbnail_url: 'https://static-cdn.jtvnw.net/previews-ttv/live_user_dansgaming-{width}x{height}.jpg',
    },
    {
      id: '444444444444',
      user_id: '7236692',
      user_name: 'BillyBob5',
      game_id: '29307',
      type: 'live',
      title: "[Punday Monday] Necromancer - Dan's First Character - Maps - !build",
      viewer_count: 5723,
      started_at: '2017-08-14T15:45:17Z',
      language: 'en',
      thumbnail_url: 'https://static-cdn.jtvnw.net/previews-ttv/live_user_dansgaming-{width}x{height}.jpg',
    },
  ],
};

export default initialState;
